### ISSUE TITLE
Feature Request: listener ports differ form target ports

### ISSUE THREAD

**Issue by stevie-** [cn-terraform/terraform-aws-ecs-alb#2]
At the moment it is not possible to have different LB listener and target group ports.

For example you can *not* forward LB port 443 to target group port 80

https://github.com/cn-terraform/terraform-aws-ecs-alb/blob/master/main.tf#L160-L179

Because the listener port is read out of the targetgroups:

```hcl
  port              = element(aws_lb_target_group.lb_http_tgs.*.port, count.index)

  port              = element(aws_lb_target_group.lb_https_tgs.*.port, count.index)
```

**Comment by jnonino** [comment]
Added in version [1.0.7](https://registry.terraform.io/modules/cn-terraform/ecs-alb/aws/1.0.7)
